name: Dev Build

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Build
        env:
          APP_VERSION: dev
        run: cargo build --release
